version: '3.8'

services:
  wa-broadcast:
    build: .
    container_name: wa-broadcast-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/google-chrome-stable
      - CHROME_PATH=/usr/bin/google-chrome-stable
    volumes:
      - ./sessions:/app/sessions
      - ./logs:/app/logs
      - /dev/shm:/dev/shm
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_ADMIN
    shm_size: 2gb
    mem_limit: 2g
    memswap_limit: 2g
    networks:
      - wa-network

  # Optional: Nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: wa-broadcast-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - wa-broadcast
    restart: unless-stopped
    networks:
      - wa-network

networks:
  wa-network:
    driver: bridge

volumes:
  sessions:
  logs: